// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DelJsonFile(arg1) {
  return window['go']['main']['App']['DelJsonFile'](arg1);
}

export function DeleteDataSource(arg1) {
  return window['go']['main']['App']['DeleteDataSource'](arg1);
}

export function GetDataSource() {
  return window['go']['main']['App']['GetDataSource']();
}

export function GetJobJson(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['GetJobJson'](arg1, arg2, arg3, arg4, arg5);
}

export function GetJsonFileList() {
  return window['go']['main']['App']['GetJsonFileList']();
}

export function GetMysqlColumn(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetMysqlColumn'](arg1, arg2, arg3);
}

export function GetMysqlDb(arg1) {
  return window['go']['main']['App']['GetMysqlDb'](arg1);
}

export function GetMysqlTable(arg1, arg2) {
  return window['go']['main']['App']['GetMysqlTable'](arg1, arg2);
}

export function GetSetting() {
  return window['go']['main']['App']['GetSetting']();
}

export function GetTxtFirstLine(arg1, arg2) {
  return window['go']['main']['App']['GetTxtFirstLine'](arg1, arg2);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function IsProcessRunning(arg1) {
  return window['go']['main']['App']['IsProcessRunning'](arg1);
}

export function KillScript(arg1) {
  return window['go']['main']['App']['KillScript'](arg1);
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function RunScript(arg1) {
  return window['go']['main']['App']['RunScript'](arg1);
}

export function SaveDataSource(arg1) {
  return window['go']['main']['App']['SaveDataSource'](arg1);
}

export function SaveFile(arg1, arg2) {
  return window['go']['main']['App']['SaveFile'](arg1, arg2);
}

export function SaveSetting(arg1) {
  return window['go']['main']['App']['SaveSetting'](arg1);
}

export function UpdateDataSource(arg1) {
  return window['go']['main']['App']['UpdateDataSource'](arg1);
}
