// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DelJsonFile(arg1:string):Promise<string>;

export function DeleteDataSource(arg1:string):Promise<string>;

export function GetDataSource():Promise<string>;

export function GetJobJson(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<string>;

export function GetJsonFileList():Promise<Array<string>>;

export function GetMysqlColumn(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GetMysqlDb(arg1:string):Promise<string>;

export function GetMysqlTable(arg1:string,arg2:string):Promise<string>;

export function GetSetting():Promise<string>;

export function GetTxtFirstLine(arg1:string,arg2:string):Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function IsProcessRunning(arg1:number):Promise<boolean>;

export function KillScript(arg1:number):Promise<string>;

export function ReadFile(arg1:string):Promise<string>;

export function RunScript(arg1:string):Promise<string>;

export function SaveDataSource(arg1:string):Promise<string>;

export function SaveFile(arg1:string,arg2:string):Promise<string>;

export function SaveSetting(arg1:string):Promise<string>;

export function UpdateDataSource(arg1:string):Promise<string>;
